In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_parquet('merged_aligned_cells.parquet')

In [4]:
df.columns

Index(['cell_id_source', 'x_centroid_source', 'y_centroid_source',
       'transcript_counts_source', 'control_probe_counts_source',
       'genomic_control_counts_source', 'control_codeword_counts_source',
       'unassigned_codeword_counts_source',
       'deprecated_codeword_counts_source', 'total_counts_source',
       'cell_area_source', 'nucleus_area_source', 'nucleus_count_source',
       'segmentation_method_source', 'cell_id_target', 'x_centroid_target',
       'y_centroid_target', 'transcript_counts_target',
       'control_probe_counts_target', 'genomic_control_counts_target',
       'control_codeword_counts_target', 'unassigned_codeword_counts_target',
       'deprecated_codeword_counts_target', 'total_counts_target',
       'cell_area_target', 'nucleus_area_target', 'nucleus_count_target',
       'segmentation_method_target', 'transformed_x_centroid',
       'transformed_y_centroid', 'common_cell_id'],
      dtype='object')

In [5]:
df.head()

,cell_id_source,x_centroid_source,y_centroid_source,transcript_counts_source,control_probe_counts_source,genomic_control_counts_source,control_codeword_counts_source,unassigned_codeword_counts_source,deprecated_codeword_counts_source,total_counts_source,...,unassigned_codeword_counts_target,deprecated_codeword_counts_target,total_counts_target,cell_area_target,nucleus_area_target,nucleus_count_target,segmentation_method_target,transformed_x_centroid,transformed_y_centroid,common_cell_id
56623,aaaadcac-1,315.479584,4135.815918,35,0,0,0,0,0,35,...,0,0,229,35.357345,6.276719,1,Segmented by interior stain (18S),321.366616,4143.094821,0
56627,aaaadcac-1,315.479584,4135.815918,35,0,0,0,0,0,35,...,0,2,242,76.855940,8.986094,1,Segmented by interior stain (18S),319.488272,4136.387428,0
56599,aaaanbhm-1,318.433136,4109.978027,292,0,0,0,0,0,292,...,0,0,305,78.030003,38.969845,1,Segmented by interior stain (18S),318.343279,4113.174245,2
1054,aaaankfe-1,335.111847,4116.146484,303,1,0,0,0,0,304,...,0,1,713,68.411721,30.615939,1,Segmented by boundary stain (ATP1A1+CD45+E-Cad...,333.459390,4109.816989,3
56602,aaaankfe-1,335.111847,4116.146484,303,1,0,0,0,0,304,...,0,0,262,47.504377,19.191407,1,Segmented by interior stain (18S),333.620910,4118.328797,3

In [6]:
df['common_cell_id'].nunique()

173745

In [7]:
useful_cols = ['common_cell_id', 'cell_id_source', 'x_centroid_source', 'y_centroid_source', 
               'cell_id_target', 'x_centroid_target', 'y_centroid_target', 
               'transformed_x_centroid', 'transformed_y_centroid']

In [8]:
df.loc[df['common_cell_id'] == 3, useful_cols]

,common_cell_id,cell_id_source,x_centroid_source,y_centroid_source,cell_id_target,x_centroid_target,y_centroid_target,transformed_x_centroid,transformed_y_centroid
1054,3,aaaankfe-1,335.111847,4116.146484,aanimnpl-1,530.556335,5111.403809,333.45939,4109.816989
56602,3,aaaankfe-1,335.111847,4116.146484,cpgdlmof-1,531.460510,5119.875977,333.62091,4118.328797

In [9]:
df.loc[df['common_cell_id'] == 71, useful_cols]

,common_cell_id,cell_id_source,x_centroid_source,y_centroid_source,cell_id_target,x_centroid_target,y_centroid_target,transformed_x_centroid,transformed_y_centroid
56472,71,aabdlmdm-1,253.868683,4209.937988,cpegacod-1,460.261566,5216.250000,255.953387,4209.471009
56474,71,aabdlmdm-1,253.868683,4209.937988,cpeglbgk-1,462.530273,5218.379395,258.023149,4211.761025
56477,71,aabdlmdm-1,253.868683,4209.937988,cpehiekd-1,450.816162,5217.738770,246.673647,4210.313049
56478,71,aabdlmdm-1,253.868683,4209.937988,cpehjggg-1,456.247833,5220.131348,251.806974,4213.085544

## many to one mapping ?
we can see that many cells are mapped to a single cell due to the **nearest neighbor approach**

In [10]:
import scanpy as sc

In [11]:
adata1 = sc.read_h5ad('sq_cell_feature_1.h5ad')
adata2 = sc.read_h5ad('sq_cell_feature_2.h5ad')

In [12]:
adata1, adata2

(AnnData object with n_obs × n_vars = 245754 × 289
     obs: 'cell_id', 'x_centroid', 'y_centroid', 'transcript_counts', 'control_probe_counts', 'genomic_control_counts', 'control_codeword_counts', 'unassigned_codeword_counts', 'deprecated_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'nucleus_count', 'segmentation_method', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'log1p_total_counts', 'pct_counts_in_top_10_genes', 'pct_counts_in_top_20_genes', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_150_genes', 'n_counts', 'leiden'
     var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells'
     uns: 'leiden', 'leiden_colors', 'log1p', 'neighbors', 'pca', 'umap'
     obsm: 'X_pca', 'X_umap', 'spatial'
     varm: 'PCs'
     obsp: 'connectivities', 'distances',
 AnnData object with n_obs × n_vars = 271693 × 5001
     obs: 'cell_id', 'x_centroid', 'y_centroid', 'transcript_counts', 'control_probe_counts', 'genomic_control_counts', 'control_codeword_counts', 'unassigned_codeword_counts', 'deprecated_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'nucleus_count', 'segmentation_method', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'log1p_total_counts', 'pct_counts_in_top_10_genes', 'pct_counts_in_top_20_genes', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_150_genes', 'n_counts', 'leiden'
     var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells'
     uns: 'leiden', 'leiden_colors', 'log1p', 'neighbors', 'pca', 'umap'
     obsm: 'X_pca', 'X_umap', 'spatial'
     varm: 'PCs'
     obsp: 'connectivities', 'distances')